openapi: 3.0.0
info:
  title: GPIG
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /actions:
    post:
      summary: ''
      operationId: post-actions-health-drive
      responses:
        '200':
          description: Actions OK
        '404':
          description: Actions Fucked
      description: Array of requested actions
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                anyOf:
                  - $ref: '#/components/schemas/healthDrive'
                  - $ref: '#/components/schemas/investHealthService'
                  - $ref: '#/components/schemas/socialDistancing'
                  - $ref: '#/components/schemas/imposeCurfew'
        description: Encourage health drive in specific location
    parameters: []
components:
  schemas:
    healthDrive:
      title: healthDrive
      type: object
      properties:
        id:
          type: integer
        mode:
          type: string
          enum:
            - create
            - delete
        location:
          type: string
      required:
        - id
        - mode
        - location
      description: Encourage healthy activity
    investHealthService:
      title: investHealthService
      type: object
      properties:
        id:
          type: integer
        mode:
          type: string
          enum:
            - create
            - update
            - delete
        amount-invested:
          type: integer
      required:
        - id
        - mode
        - amount-invested
      description: Increase investment in health services
    socialDistancing:
      title: socialDistancing
      type: object
      properties:
        id:
          type: integer
        mode:
          type: string
          enum:
            - create
            - update
            - delete
        distance:
          type: integer
        location:
          type: string
      required:
        - id
        - mode
        - distance
        - location
      description: Introduce social distancing rules
    imposeCurfew:
      title: imposeCurfew
      type: object
      properties:
        id:
          type: string
        mode:
          type: string
          enum:
            - create
            - delete
        location:
          type: string
      required:
        - id
        - mode
        - location
      description: Introduce curfew to require individuals to not go into public places past a certain time
